### ISSUE TITLE
[Security] Potential Secret Leak

### ISSUE THREAD

**Issue by raima-zachariah** [erasmosoares/erasmosoares#1]
It has been noticed that while using athul/waka-readme@master your WAKATIME_API_KEY 8cb730fb-2878-4fa6-bbca-ba68d13cb604 is present in plaintext. Please ensure that secrets are encrypted or not passed as plain text in github workflows.

**Comment by erasmosoares** [comment]
Fixed by using the configured secrets.WAKATIME_API_KEY @raima-zachariah
